sudo: true

language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - g++-7
            - cmake-data
            - cmake
            - libgtest-dev
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
  - eval "${MATRIX_EVAL}"

install:
  - ./install-gtest.sh

script:
  - cmake .
  - cmake --build .
  - ctest
